# This inventory describe a HA typology with stacked etcd (== same nodes as control plane)
# and 3 worker nodes
# See https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html
# for tips on building your # inventory

# Configure 'ip' variable to bind kubernetes services on a different ip than the default iface
# We should set etcd_member_name for etcd cluster. The node that are not etcd members do not need to set the value,
# or can set the empty string value.
[kube_control_plane]
master-seang  ansible_host=34.126.125.84  ip=10.148.0.7  etcd_member_name=etcd1


[etcd:children]
kube_control_plane

[kube_node]
worker01 ansible_host=34.22.93.174  #ip=10.178.0.39
worker02 ansible_host=34.129.8.124  #ip=10.192.0.7
worker03 ansible_host=34.126.203.159  #ip=10.192.0.8

